config/routes.rb
Rails.application.routes.draw do
  root "patients#index"
  resources :patients
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
    validates :name, presence: true
    validates :date, presence: true
    validates :od, presence: true
    validates :os, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end

   def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
  end

  def create 
    @patient = Patient.new(patient_params)
    
    if @patient.save 
      redirect_to @patient
    else 
      render :new
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])

    if @patient.update(patient_params)
      redirect_to @patient
    else
      render :edit
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    redirect_to root_path
  end

  private
    def patient_params
      params.require(:patient).permit(:name, :date, :od, :os, :add, :assessment)
    end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Patient Records App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="h-64 bg-gradient-to-r from-fuchsia-50  to-warm-gray-200">
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<h1 class="text-center text-6xl m-40">Add Patient Form</h1>
<div class="
            justify-center 
            items-center 
            w-full 
            max-w-lg 
            bg-blue-200">

  <%= form_with model: patient do |form| %>


  <div class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
    Patient Name: 
    <%= form.text_field :name %>
    <% patient.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <div>
    Date of Consultation
    <%= form.text_area :date %>
    <% patient.errors.full_messages_for(:date).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <div>
    Right Eye (OD)

    <%= form.text_area :od %>
    <% patient.errors.full_messages_for(:od).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <div>
    Left Eye (OS)

    <%= form.text_area :os %>
    <% patient.errors.full_messages_for(:os).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <div>
    Add

    <%= form.text_area :add %>
  </div>

  <div>
    Assessment

    <%= form.text_area :assessment %>
  </div>

  <button>
    <%= form.submit %>
  </button>
</div>
<% end %>
<%= link_to "Home", root_path(@patient)%>

app/views/patients/edit.html.erb
<h1>Edit Patient Form</h1>

<%= render "form", patient: @patient %>

app/views/patients/index.html.erb
<h1 class="text-center text-6xl m-40">Patients Record List</h1>


<div class="container flex justify-center mx-auto">
    <div class="flex flex-col">
        <div class="w-full">
            <div class="border-b border-gray-200 shadow">
                <table class="divide-y divide-gray-300 ">
                    <thead class="bg-gray-50">
                        <tr>

                            <th class="px-6 py-2 text-xs text-gray-500">
                                Name
                            </th>
                            <th class="px-6 py-2 text-xs text-gray-500">
                                Date of Consultation
                            </th>

                            <th class="px-6 py-2 text-xs text-gray-500"> 
                            </th>
                            <th class="px-6 py-2 text-xs text-gray-500">
                                Actions
                            </th>
                            <th class="px-6 py-2 text-xs text-gray-500">
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-300">
                        <tr class="whitespace-nowrap">
						<% @patients.each do |patient| %>
                            <td class="px-6 py-4">
                                <div class="text-sm text-gray-900">
                                    <%= patient.name %>
                                </div>
                            </td>
                            <td class="px-6 py-4">
                                <div class="text-sm text-gray-500"><%= patient.date %></div>
                            </td>
                            <td class="px-6 py-4">
                                <button class="px-4 py-1 text-sm text-white bg-blue-400 hover:bg-blue-800 rounded-full"><%= link_to "View", patient %></button>
                            </td>
                            <td class="px-6 py-4">
                                <button class="px-4 py-1 text-sm text-white bg-blue-400 hover:bg-blue-800 rounded-full"><%= link_to "Edit", edit_patient_path(patient)%></button>
                            </td>
                            <td class="px-6 py-4">
                                <button class="px-4 py-1 text-sm text-white bg-red-500 hover:bg-red-800 rounded-full"><%= link_to "Delete", patient, method: :delete%></button> 
                            </td>
						
                        </tr>
                    <% end %>
                    </tbody>
                </table>


            </div>
        </div>
                        <button type="button" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded w-full"><%= link_to "Add patient", new_patient_path %></button>
    </div>
</div>
	

app/views/patients/new.html.erb
<h1>Add Patient</h1>

<%= render "form", patient: @patient %>

app/views/patients/show.html.erb
<div class="wrapper flex-shrink-0 antialiased text-gray-900">
<div>
    
 <div class="relative px-4 -mt-16  ">
   <div class="bg-white p-6 rounded-lg shadow-lg">
    <div class="flex items-baseline">

      <div class="ml-2 text-gray-600 uppercase text-xs font-semibold tracking-wider">
    <%= @patient.date %></p>
  </div>  
    </div>
    
    <h4 class="mt-1 text-xl font-semibold uppercase leading-tight truncate"><%= @patient.name %></h4>
 <br>
  <div class="mt-1">
    RIGHT EYE: 
    <span class="text-gray-600 text-sm"> <%= @patient.od %></span>
  </div>
    <div class="mt-1">
    LEFT EYE: 
    <span class="text-gray-600 text-sm"> <%= @patient.os %></span>
  </div>
    <div class="mt-1">
    ADD: 
    <span class="text-gray-600 text-sm"> <%= @patient.add %></span>
  </div>
  <div class="mt-4">
    <span class="text-sm text-gray-600"><%= @patient.assessment %></span>
  </div>  
  </div>
<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded w-auto"><%= link_to "Edit", edit_patient_path(@patient) %></button>
<button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded w-auto"><%= link_to "Delete", patient_path(@patient), method: :delete %></button>
 </div>
<button class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded w-auto"><%= link_to "Home", root_path(@patient)%></button>
  

	</div>
</div>